---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample
data:
  URL: gotomeeting.com
  timing: 7:30AM IST
  course: DevOps
---
apiVersion: v1
kind: Pod
metadata:
  name: sample2
spec:
  containers:
    - name: centos
      image: centos:7
      command: ["sleep", "10000"]
#      envFrom:
#        - configMapRef:
#            name: sample