---
apiVersion: v1
kind: pod
metadata:
  name: healthcheck
spec:
  containers:
    -name: health
     image: nikkaushal/healthcheck
     livenessProbe:
       exec:
         command:
           - cat
           - /opt/file.txt
         initialDelaySeconds: 5
         periodSeconds: 5